## Filebeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/filebeat.docker.yml
#

name: filebeat

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    # The Docker autodiscover provider automatically retrieves logs from Docker
    # containers as they start and stop.
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/docker/containers/${data.container.id}/*-json.log
      templates:
        - condition:
            contains:
              docker.container.image: elasticsearch
          config:
            - module: elasticsearch
              server:
                input:
                  type: container
                  paths:
                    - /var/lib/docker/containers/${data.container.id}/*-json.log

processors:
  - add_cloud_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    username: beats_system
    password: ${BEATS_SYSTEM_PASSWORD}

output.elasticsearch:
  hosts: [ http://elasticsearch:9200 ]
  username: filebeat_internal
  password: ${FILEBEAT_INTERNAL_PASSWORD}

# output.logstash:
#   hosts: ["localhost:5044"]

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/filebeat/current/http-endpoint.html
#

http:
  enabled: true
  host: 0.0.0.0

# filebeat.inputs:
# - type: filestream
#   id: docker-logs
#   paths:
#     - /var/lib/docker/containers/*/*.log
#   parsers:
#     - container: ~

# processors:
#   - add_docker_metadata:
#       host: "unix:///var/run/docker.sock"
#   - decode_json_fields:
#       fields: ["message", "log"]
#       target: ""
#       overwrite_keys: true
#   - drop_event:
#       when:
#         contains:
#           container.image.name: "docker.elastic.co/logstash/logstash"
#   - rename:
#       fields:
#         - from: "container.name"
#           to: "service.name"
#       ignore_missing: true

# output.logstash:
#   hosts: ["logstash:5044"]

# logging.level: debug
# logging.to_files: true
# logging.files:
#   path: /usr/share/filebeat/logs
#   name: filebeat.log
#   keepfiles: 7
#   permissions: 0644

# setup.ilm.enabled: false
# setup.template.enabled: false
