FROM prom/prometheus:v3.2.0

LABEL maintainer="Pierre MAGNERON <pmagnero@student.42.fr>"
LABEL version="1.0"
LABEL description="Prometheus part of the Monitoring stack"

####### For Debug purpose #######
# RUN pwd
# RUN whoami
# RUN ls -la

# COPY --chown=elasticsearch:elasticsearch elasticsearch.yml /usr/share/elasticsearch/config/

# USER root

# RUN chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data

# USER elasticsearch

# USER root

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu